import {
  FaMap,
  FaUtensils,
  FaHiking,
  FaFilm,
  FaBasketballBall,
  FaPaintBrush,
  FaGamepad,
  FaSpa,
  FaBook,
  FaLaptopCode,
  FaBirthdayCake,
  FaTv,
  FaCoffee,
  FaMusic,
} from "react-icons/fa";
export const moods = [
  { mood: "Exploration", icon: FaMap },
  { mood: "Eat Out", icon: FaUtensils },
  { mood: "Outdoor Activities", icon: FaHiking },
  { mood: "Entertainment", icon: FaFilm },
  { mood: "Sports and Fitness", icon: FaBasketballBall },
  { mood: "Creative", icon: FaPaintBrush },
  { mood: "Gaming", icon: FaGamepad },
  { mood: "Relaxation", icon: FaSpa },
  { mood: "Learning Experience", icon: FaBook },
  { mood: "Work", icon: FaLaptopCode },
  { mood: "Party", icon: FaBirthdayCake },
  { mood: "Chill", icon: FaTv },
  { mood: "Socializing", icon: FaCoffee },
  { mood: "Music", icon: FaMusic },
];
